### ISSUE TITLE
Handle openai.error.RateLimitError error

### ISSUE THREAD

**Issue by dmikushin** [parallelo3301/zulip-chatgpt-bot#3]
Hi, thanks for the great project!

Would it be possible to handle the openai.error.RateLimitError below, without crashing the Zulip bot entirely?

```
INFO:openai:error_code=None error_message='That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 3c7aac3c08c96827d2c150b0cd44dece in your message.)' error_param=None error_type=server_error message='OpenAI API error received' stream_error=False
Traceback (most recent call last):
  File "./bot.py", line 401, in <module>
    main()
  File "./bot.py", line 397, in main
    client.call_on_each_event(handle_message, event_types=['message'])
  File "/home/marcusmae/forge/zulip-chatgpt-bot/env/lib/python3.8/site-packages/zulip/__init__.py", line 826, in call_on_each_event
    callback(event)
  File "./bot.py", line 376, in handle_message
    response = get_gpt_response(messages, model=model)
  File "./bot.py", line 77, in get_gpt_response
    response = openai.ChatCompletion.create(
  File "/home/marcusmae/forge/zulip-chatgpt-bot/env/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/marcusmae/forge/zulip-chatgpt-bot/env/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/marcusmae/forge/zulip-chatgpt-bot/env/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/marcusmae/forge/zulip-chatgpt-bot/env/lib/python3.8/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/marcusmae/forge/zulip-chatgpt-bot/env/lib/python3.8/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 3c7aac3c08c96827d2c150b0cd44dece in your message.)
```

**Comment by parallelo3301** [comment]
Hey, bot should now not fail and will notify the user about API error. See this commit: [https://github.com/parallelo3301/zulip-chatgpt-bot/commit/de7ac26c8904cc6181ee8e10e3c502ee682defec](https://github.com/parallelo3301/zulip-chatgpt-bot/commit/de7ac26c8904cc6181ee8e10e3c502ee682defec). Let me know in case of any issue.
